@startuml
 (*)--> [上游企业发起业务申请] "提交业务申请"
 --> [核心企业待审核业务申请] "核心企业审核业务申请"
 if "核心企业审核通过" then
 --> [平台待审核业务申请] "平台审核业务申请"
         if "平台审核通过" then
           --> "核心企业补充下游业务"
              if "平台审核下游业务通过" then
                --> 资金方待审核下游业务
                  if "资金方审核下游业务通过" then
                    --> "核心企业待上传融资还款协议"
                      if "平台审核融资协议通过" then
                       --> [业务申请结束] (*)
                      else
                       -right-> "平台审核融资协议未通过"
                       -up-> "核心企业待上传融资还款协议"
                      endif
                  else
                -right-> 资金方审核下游信息未通过
                -up-> 核心企业补充下游业务
                  end if
              else
                -right-> 平台审核下游信息未通过
                -up-> 核心企业补充下游业务
              end if
         else
           -right-> [平台审核不通过] "平台审核不通过"
           -up-> "提交业务申请"
         end if
else
 -right-> [核心企业审核不通过] "核心企业审核不通过"
 -up-> "提交业务申请"
 end if
@enduml


